
spring.datasource:
  url: jdbc:mysql://localhost:8090/DB
  username: root
  password: password
  hikari.maximum-pool-size: 20

spring.jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  show-sql: true
  hibernate.ddl-auto: update

#RabbitMQ settings
spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

rabbitmq:
  exchange: rabbitmq.exchange
  queue: rabbitmq.queue
  routing.key: rabbitmq.routing-key

image.path: F:/EnkaizenTest/image-upload-server/image/